spring:
  timezone=Asia/Seoul:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        generate_statistics: false
        default_batch_fetch_size: 200
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 100
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-id
            client-secret: google-secret
            scope:
              - email
              - profile


          kakao:
            client-id: kakaoid
            client-secret: kakaosecret
            redirect-uri: http://userpark-env.eba-fmwpsjez.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao


        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  issuer: dlalstn@gmail.com
  secret_key: jwt-key

cloud:
  aws:
    s3:
      bucket: used-park
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: access
      secret-key: secret


logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.SQL_SLOW: INFO